default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_manager_development

test:
  <<: *default
  database: library_manager_test

production:
  <<: *default
  database: library_manager_production
  username: library_manager
  password: <%= ENV["LIBRARY_MANAGER_DATABASE_PASSWORD"] %>
